/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Sign in an existing user and start a session */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Sign out the current user and end the session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get the currently authenticated user */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Register a new user and start a session */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all categories. */
        get: operations["listCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List orders of the current user. */
        get: operations["listOrders"];
        put?: never;
        /** @description Create a new order from the current cart. */
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a single order by id. */
        get: operations["getOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List products with filters and pagination. */
        get: operations["listProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a single product by slug. */
        get: operations["getProduct"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/promos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List promo blocks for the home page. */
        get: operations["listPromos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Common API error format shared by all endpoints */
        ApiError: {
            code: string;
            message: string;
        };
        /** @description Product category. */
        Category: {
            /** Format: int32 */
            id: number;
            slug: string;
            name: string;
        };
        /** @description Payload for order creation. Contains no prices. */
        CreateOrderRequest: {
            /** @enum {string} */
            method: "delivery" | "pickup";
            name: string;
            phone: string;
            address?: string;
            items: components["schemas"]["OrderItemInput"][];
        };
        /**
         * @description Delivery or pickup.
         * @enum {string}
         */
        DeliveryMethod: "delivery" | "pickup";
        /** @description Payload for user sign-in. */
        LoginRequest: {
            email: string;
            password: string;
        };
        /** @description Money amount in rubles */
        Money: {
            /** Format: int32 */
            amount: number;
        };
        /** @description A completed order. */
        Order: {
            /** Format: int32 */
            id: number;
            status: string;
            createdAt: string;
            method: string;
            name: string;
            phone: string;
            address: string | null;
            total: components["schemas"]["Money"];
            items: components["schemas"]["OrderItem"][];
        };
        /** @description Order was rejected because some products are unavailable. */
        OrderError: {
            unavailable: components["schemas"]["OrderErrorItem"][];
        } & components["schemas"]["ApiError"];
        /** @description Problematic item that blocked an order. */
        OrderErrorItem: {
            slug: string;
            reason: string;
        };
        /** @description Snapshot of a product inside an order. */
        OrderItem: {
            /** Format: int32 */
            productId: number;
            name: string;
            price: components["schemas"]["Money"];
            /** Format: int32 */
            quantity: number;
        };
        /** @description Single item of a create order request. */
        OrderItemInput: {
            slug: string;
            /** Format: int32 */
            quantity: number;
        };
        /**
         * @description Order status.
         * @enum {string}
         */
        OrderStatus: "paid";
        /** @description Product in the catalog. */
        Product: {
            /** Format: int32 */
            id: number;
            slug: string;
            name: string;
            description: string;
            price: components["schemas"]["Money"];
            inStock: boolean;
            imageUrl: string | null;
            category: components["schemas"]["Category"];
        };
        /** @description Paginated list of products. */
        ProductList: {
            items: components["schemas"]["Product"][];
            /** Format: int32 */
            total: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
        };
        /** @description Promo block shown on the home page. Links to a single product. */
        PromoBlock: {
            /** Format: int32 */
            id: number;
            title: string;
            text: string;
            product: components["schemas"]["Product"];
        };
        /** @description Payload for user registration. */
        RegisterRequest: {
            email: string;
            password: string;
        };
        /** @description User account. */
        User: {
            /** Format: int32 */
            id: number;
            email: string;
        };
    };
    responses: never;
    parameters: {
        /** @description Only products in stock. */
        "ProductListParams.available": boolean;
        /** @description Category slug. Empty means all categories. */
        "ProductListParams.category": string;
        /** @description Page number, 1-based. */
        "ProductListParams.page": number;
        /** @description Maximum price in whole rubles. */
        "ProductListParams.priceMax": number;
        /** @description Minimum price in whole rubles. */
        "ProductListParams.priceMin": number;
        /** @description Search by product name. */
        "ProductListParams.search": string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"] | components["schemas"]["ApiError"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"] | components["schemas"]["ApiError"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status: string;
                    };
                };
            };
        };
    };
    listOrders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"][];
                };
            };
        };
    };
    createOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderError"];
                };
            };
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"] | components["schemas"]["ApiError"];
                };
            };
        };
    };
    listProducts: {
        parameters: {
            query?: {
                /** @description Category slug. Empty means all categories. */
                category?: components["parameters"]["ProductListParams.category"];
                /** @description Minimum price in whole rubles. */
                priceMin?: components["parameters"]["ProductListParams.priceMin"];
                /** @description Maximum price in whole rubles. */
                priceMax?: components["parameters"]["ProductListParams.priceMax"];
                /** @description Only products in stock. */
                available?: components["parameters"]["ProductListParams.available"];
                /** @description Search by product name. */
                search?: components["parameters"]["ProductListParams.search"];
                /** @description Page number, 1-based. */
                page?: components["parameters"]["ProductListParams.page"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductList"] | components["schemas"]["ApiError"];
                };
            };
        };
    };
    getProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"] | components["schemas"]["ApiError"];
                };
            };
        };
    };
    listPromos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromoBlock"][];
                };
            };
        };
    };
}
